// <auto-generated />
using System;
using Laraue.Apps.Boards.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laraue.Apps.Boards.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260825234505_AddRetros")]
    partial class AddRetros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("PreviewFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("preview_file_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_attachments_file_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_attachments_owner_id");

                    b.HasIndex("PreviewFileId")
                        .HasDatabaseName("ix_attachments_preview_file_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Attribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttributeType")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_type");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_attributes");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_attributes_organization_id");

                    b.ToTable("attributes", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.AttributeListValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_attribute_list_values");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_attribute_list_values_attribute_id");

                    b.ToTable("attribute_list_values", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.DirectSpacePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanCreateEpics")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create_epics");

                    b.Property<bool>("CanCreateIssues")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create_issues");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanDeleteEpics")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete_epics");

                    b.Property<bool>("CanDeleteIssues")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete_issues");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update");

                    b.Property<bool>("CanUpdateEpics")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update_epics");

                    b.Property<bool>("CanUpdateIssues")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update_issues");

                    b.Property<long>("OrganizationUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_user_id");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("pk_direct_space_permissions");

                    b.HasIndex("OrganizationUserId")
                        .HasDatabaseName("ix_direct_space_permissions_organization_user_id");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_direct_space_permissions_space_id");

                    b.ToTable("direct_space_permissions", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Epic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("space_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TouchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("touched_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_epics");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_epics_space_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_epics_user_id");

                    b.ToTable("epics", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("Content")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LexoRank")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character(34)")
                        .HasColumnName("lexo_rank")
                        .IsFixedLength()
                        .UseCollation("C");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("status_id");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_message_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_issues_assignee_id");

                    b.HasIndex("Content")
                        .HasDatabaseName("ix_issues_content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Content"), new[] { "gin_trgm_ops" });

                    b.HasIndex("LexoRank")
                        .HasDatabaseName("ix_issues_lexo_rank");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_issues_owner_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_issues_status_id");

                    b.HasIndex("TelegramMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_telegram_message_id");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttachment", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.HasKey("IssueId", "AttachmentId")
                        .HasName("pk_issue_attachments");

                    b.HasIndex("AttachmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_attachments_attachment_id");

                    b.ToTable("issue_attachments", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeDateTimeValue", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<DateTime>("Value")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value");

                    b.HasKey("IssueId", "AttributeId")
                        .HasName("pk_issue_attribute_date_time_values");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_issue_attribute_date_time_values_attribute_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_issue_attribute_date_time_values_value");

                    b.ToTable("issue_attribute_date_time_values", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeDateValue", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<DateOnly>("Value")
                        .HasColumnType("date")
                        .HasColumnName("value");

                    b.HasKey("IssueId", "AttributeId")
                        .HasName("pk_issue_attribute_date_values");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_issue_attribute_date_values_attribute_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_issue_attribute_date_values_value");

                    b.ToTable("issue_attribute_date_values", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeDecimalValue", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("IssueId", "AttributeId")
                        .HasName("pk_issue_attribute_decimal_values");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_issue_attribute_decimal_values_attribute_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_issue_attribute_decimal_values_value");

                    b.ToTable("issue_attribute_decimal_values", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeIntegerValue", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("IssueId", "AttributeId")
                        .HasName("pk_issue_attribute_integer_values");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_issue_attribute_integer_values_attribute_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_issue_attribute_integer_values_value");

                    b.ToTable("issue_attribute_integer_values", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeListValue", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<long>("AttributeListValueId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_list_value_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.HasKey("IssueId", "AttributeId")
                        .HasName("pk_issue_attribute_list_values");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_issue_attribute_list_values_attribute_id");

                    b.HasIndex("AttributeListValueId")
                        .HasDatabaseName("ix_issue_attribute_list_values_attribute_list_value_id");

                    b.ToTable("issue_attribute_list_values", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeTextValue", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("IssueId", "AttributeId")
                        .HasName("pk_issue_attribute_text_values");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_issue_attribute_text_values_attribute_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_issue_attribute_text_values_value");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Value"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Value"), new[] { "gin_trgm_ops" });

                    b.ToTable("issue_attribute_text_values", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_issue_comments");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_issue_comments_issue_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_issue_comments_owner_id");

                    b.ToTable("issue_comments", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueCommentAttachment", b =>
                {
                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.HasKey("CommentId", "AttachmentId")
                        .HasName("pk_issue_comments_attachments");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_issue_comments_attachments_attachment_id");

                    b.ToTable("issue_comments_attachments", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueNumber", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("space_id");

                    b.HasKey("IssueId")
                        .HasName("pk_issue_numbers");

                    b.HasIndex("SpaceId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_numbers_space_id_number");

                    b.ToTable("issue_numbers", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.LinkedTelegramChat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExternalChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_chat_id");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("SaveMode")
                        .HasColumnType("integer")
                        .HasColumnName("save_mode");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UnlinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlinked_at");

                    b.HasKey("Id")
                        .HasName("pk_linked_telegram_chats");

                    b.HasIndex("ExternalChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_linked_telegram_chats_external_chat_id");

                    b.HasIndex("LinkedAt")
                        .HasDatabaseName("ix_linked_telegram_chats_linked_at");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_linked_telegram_chats_owner_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_linked_telegram_chats_status_id");

                    b.HasIndex("UnlinkedAt")
                        .HasDatabaseName("ix_linked_telegram_chats_unlinked_at");

                    b.ToTable("linked_telegram_chats", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("JoinCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("SlugPostfix")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("slug_postfix");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_join_code");

                    b.HasIndex("OwnerId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_owner_id_type")
                        .HasFilter("type = 1");

                    b.HasIndex("SlugPostfix", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug_postfix_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.OrganizationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_logs");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_organization_logs_owner_id");

                    b.HasIndex("EntityId", "EntityType")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_organization_logs_entity_id_entity_type");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_organization_logs_organization_id_created_at");

                    b.HasIndex("OrganizationId", "OwnerId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_organization_logs_organization_id_owner_id_created_at");

                    b.ToTable("organization_logs", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.OrganizationLogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("NewDisplayValue")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("new_display_value");

                    b.Property<string>("NewValueId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("new_value_id");

                    b.Property<string>("OldDisplayValue")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("old_display_value");

                    b.Property<string>("OldValueId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("old_value_id");

                    b.Property<long>("OrganizationLogId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_log_id");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_id");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("property_name");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.HasKey("Id")
                        .HasName("pk_organization_log_items");

                    b.HasIndex("OrganizationLogId")
                        .HasDatabaseName("ix_organization_log_items_organization_log_id");

                    b.ToTable("organization_log_items", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.OrganizationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("AdminAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("admin_access_level");

                    b.Property<bool>("CanCreateEpics")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create_epics");

                    b.Property<bool>("CanCreateIssues")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create_issues");

                    b.Property<bool>("CanCreateSpaces")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create_spaces");

                    b.Property<bool>("CanDeleteEpics")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete_epics");

                    b.Property<bool>("CanDeleteIssues")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete_issues");

                    b.Property<bool>("CanDeleteSpaces")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete_spaces");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanUpdateEpics")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update_epics");

                    b.Property<bool>("CanUpdateIssues")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update_issues");

                    b.Property<bool>("CanUpdateSpaces")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update_spaces");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_users");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_users_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_users_user_id");

                    b.ToTable("organization_users", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Retro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Phase")
                        .HasColumnType("integer")
                        .HasColumnName("phase");

                    b.Property<DateTime?>("VoteEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vote_ends_at");

                    b.Property<int>("VotesPerUser")
                        .HasColumnType("integer")
                        .HasColumnName("votes_per_user");

                    b.HasKey("Id")
                        .HasName("pk_retros");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_retros_owner_id");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_retros_organization_id_created_at");

                    b.ToTable("retros", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<bool>("Revealed")
                        .HasColumnType("boolean")
                        .HasColumnName("revealed");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("text");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_retro_cards");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_retro_cards_author_id");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_retro_cards_section_id");

                    b.ToTable("retro_cards", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroCardVote", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CardId", "UserId")
                        .HasName("pk_retro_card_votes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_retro_card_votes_user_id");

                    b.ToTable("retro_card_votes", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroParticipant", b =>
                {
                    b.Property<long>("RetroId")
                        .HasColumnType("bigint")
                        .HasColumnName("retro_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RetroId", "UserId")
                        .HasName("pk_retro_participants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_retro_participants_user_id");

                    b.ToTable("retro_participants", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("RetroId")
                        .HasColumnType("bigint")
                        .HasColumnName("retro_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_retro_sections");

                    b.HasIndex("RetroId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_retro_sections_retro_id_sort_order");

                    b.ToTable("retro_sections", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Space", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_spaces");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_spaces_creator_id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_spaces_organization_id_key");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.SpaceCounter", b =>
                {
                    b.Property<long>("SpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("space_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SpaceId"));

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.HasKey("SpaceId")
                        .HasName("pk_space_counters");

                    b.ToTable("space_counters", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<long>("EpicId")
                        .HasColumnType("bigint")
                        .HasColumnName("epic_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_statuses");

                    b.HasIndex("EpicId")
                        .HasDatabaseName("ix_statuses_epic_id");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.TelegramFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalFileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_file_id");

                    b.Property<string>("ExternalFileUniqueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_file_unique_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_files");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_files_file_id");

                    b.ToTable("telegram_files", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.TelegramMediaGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_media_groups");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_media_groups_external_id");

                    b.ToTable("telegram_media_groups", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.TelegramMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<long>("ExternalChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_chat_id");

                    b.Property<int>("ExternalMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("external_message_id");

                    b.Property<long?>("LinkedTelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("linked_telegram_chat_id");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<long?>("TelegramMediaGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_media_group_id");

                    b.Property<string>("Text")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_telegram_messages");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_telegram_messages_attachment_id");

                    b.HasIndex("LinkedTelegramChatId")
                        .HasDatabaseName("ix_telegram_messages_linked_telegram_chat_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_telegram_messages_sender_id");

                    b.HasIndex("TelegramMediaGroupId")
                        .HasDatabaseName("ix_telegram_messages_telegram_media_group_id");

                    b.HasIndex("ExternalMessageId", "ExternalChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_messages_external_message_id_external_chat_id");

                    b.ToTable("telegram_messages", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(129)
                        .HasColumnType("character varying(129)")
                        .HasColumnName("display_name");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("initials");

                    b.Property<string>("TelegramFirstName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_first_name");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramLanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("telegram_language_code");

                    b.Property<string>("TelegramLastName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_last_name");

                    b.Property<string>("TelegramUserName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.UserOnboarding", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("OnboardingId")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId", "OnboardingId")
                        .HasName("pk_user_onboardings");

                    b.ToTable("user_onboardings", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.UserOrganizationPreferences", b =>
                {
                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long?>("SelectedSpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("selected_space_id");

                    b.HasKey("OrganizationId", "UserId")
                        .HasName("pk_user_organization_preferences");

                    b.ToTable("user_organization_preferences", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("EpicSortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("epic_sort_order");

                    b.HasKey("UserId")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.Interceptors.EFCore.InterceptorStateModel<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ActiveInterceptor")
                        .HasColumnType("text")
                        .HasColumnName("active_interceptor");

                    b.Property<string>("InterceptorContext")
                        .HasColumnType("text")
                        .HasColumnName("interceptor_context");

                    b.HasKey("UserId")
                        .HasName("pk_interceptor_state");

                    b.ToTable("interceptor_state", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.FailedUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_failed_updates");

                    b.ToTable("failed_updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.Update", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.HasKey("Id")
                        .HasName("pk_updates");

                    b.ToTable("updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Attachment", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_files_file_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_users_owner_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.File", "PreviewFile")
                        .WithMany()
                        .HasForeignKey("PreviewFileId")
                        .HasConstraintName("fk_attachments_files_preview_file_id");

                    b.Navigation("File");

                    b.Navigation("Owner");

                    b.Navigation("PreviewFile");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Attribute", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Organization", "Organization")
                        .WithMany("Attributes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attributes_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.AttributeListValue", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attribute", "Attribute")
                        .WithMany("AttributeListValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_list_values_attributes_attribute_id");

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.DirectSpacePermission", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.OrganizationUser", "OrganizationUser")
                        .WithMany()
                        .HasForeignKey("OrganizationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direct_space_permissions_organization_users_organization_us");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Space", "Space")
                        .WithMany("Users")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direct_space_permissions_spaces_space_id");

                    b.Navigation("OrganizationUser");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Epic", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Space", "Space")
                        .WithMany("Epics")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epics_spaces_space_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "User")
                        .WithMany("Epics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epics_users_user_id");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Issue", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_users_assignee_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_users_owner_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Status", "Status")
                        .WithMany("Issues")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_statuses_status_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.TelegramMessage", "TelegramMessage")
                        .WithOne("Issue")
                        .HasForeignKey("Laraue.Apps.Boards.DataAccess.Models.Issue", "TelegramMessageId")
                        .HasConstraintName("fk_issues_telegram_messages_telegram_message_id");

                    b.Navigation("Assignee");

                    b.Navigation("Owner");

                    b.Navigation("Status");

                    b.Navigation("TelegramMessage");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttachment", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attachment", "Attachment")
                        .WithOne("IssueAttachment")
                        .HasForeignKey("Laraue.Apps.Boards.DataAccess.Models.IssueAttachment", "AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attachments_attachments_attachment_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithMany("IssueAttachments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attachments_issues_issue_id");

                    b.Navigation("Attachment");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeDateTimeValue", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_date_time_values_attributes_attribute_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithMany("DateTimeAttributes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_date_time_values_issues_issue_id");

                    b.Navigation("Attribute");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeDateValue", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_date_values_attributes_attribute_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithMany("DateAttributes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_date_values_issues_issue_id");

                    b.Navigation("Attribute");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeDecimalValue", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_decimal_values_attributes_attribute_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithMany("DecimalAttributes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_decimal_values_issues_issue_id");

                    b.Navigation("Attribute");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeIntegerValue", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_integer_values_attributes_attribute_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithMany("IntegerAttributes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_integer_values_issues_issue_id");

                    b.Navigation("Attribute");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeListValue", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_list_values_attributes_attribute_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.AttributeListValue", "AttributeListValue")
                        .WithMany()
                        .HasForeignKey("AttributeListValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_list_values_attribute_list_values_attribute");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithMany("ListAttributes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_list_values_issues_issue_id");

                    b.Navigation("Attribute");

                    b.Navigation("AttributeListValue");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueAttributeTextValue", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_text_values_attributes_attribute_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithMany("TextAttributes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attribute_text_values_issues_issue_id");

                    b.Navigation("Attribute");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueComment", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithMany("IssueComments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_comments_issues_issue_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_comments_users_owner_id");

                    b.Navigation("Issue");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueCommentAttachment", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_comments_attachments_attachments_attachment_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.IssueComment", "Comment")
                        .WithMany("Attachments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_comments_attachments_issue_comments_comment_id");

                    b.Navigation("Attachment");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueNumber", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Issue", "Issue")
                        .WithOne("IssueNumber")
                        .HasForeignKey("Laraue.Apps.Boards.DataAccess.Models.IssueNumber", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_numbers_issues_issue_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_numbers_spaces_space_id");

                    b.Navigation("Issue");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.LinkedTelegramChat", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("fk_linked_telegram_chats_users_owner_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_linked_telegram_chats_statuses_status_id");

                    b.Navigation("Owner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Organization", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Owner")
                        .WithMany("Organizations")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.OrganizationLog", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_logs_organizations_organization_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_logs_users_owner_id");

                    b.Navigation("Organization");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.OrganizationLogItem", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.OrganizationLog", "OrganizationLog")
                        .WithMany("Items")
                        .HasForeignKey("OrganizationLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_log_items_organization_logs_organization_log_id");

                    b.Navigation("OrganizationLog");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.OrganizationUser", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_organizations_organization_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_users_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Retro", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retros_organizations_organization_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retros_users_owner_id");

                    b.Navigation("Organization");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroCard", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_cards_users_author_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.RetroSection", "Section")
                        .WithMany("Cards")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_cards_retro_sections_section_id");

                    b.Navigation("Author");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroCardVote", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.RetroCard", "Card")
                        .WithMany("Votes")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_card_votes_retro_cards_card_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_card_votes_users_user_id");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroParticipant", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Retro", "Retro")
                        .WithMany("Participants")
                        .HasForeignKey("RetroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_participants_retros_retro_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_participants_users_user_id");

                    b.Navigation("Retro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroSection", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Retro", "Retro")
                        .WithMany("Sections")
                        .HasForeignKey("RetroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_sections_retros_retro_id");

                    b.Navigation("Retro");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Space", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Creator")
                        .WithMany("Spaces")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_users_creator_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Organization", "Organization")
                        .WithMany("Spaces")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_organizations_organization_id");

                    b.Navigation("Creator");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Status", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Epic", "Epic")
                        .WithMany("Statuses")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_statuses_epics_epic_id");

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.TelegramFile", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.File", "File")
                        .WithOne("TelegramFile")
                        .HasForeignKey("Laraue.Apps.Boards.DataAccess.Models.TelegramFile", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_files_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.TelegramMessage", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .HasConstraintName("fk_telegram_messages_attachments_attachment_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.LinkedTelegramChat", "LinkedTelegramChat")
                        .WithMany()
                        .HasForeignKey("LinkedTelegramChatId")
                        .HasConstraintName("fk_telegram_messages_linked_telegram_chats_linked_telegram_cha");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .HasConstraintName("fk_telegram_messages_users_sender_id");

                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.TelegramMediaGroup", "TelegramMediaGroup")
                        .WithMany()
                        .HasForeignKey("TelegramMediaGroupId")
                        .HasConstraintName("fk_telegram_messages_telegram_media_groups_telegram_media_grou");

                    b.Navigation("Attachment");

                    b.Navigation("LinkedTelegramChat");

                    b.Navigation("Sender");

                    b.Navigation("TelegramMediaGroup");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.UserOnboarding", b =>
                {
                    b.HasOne("Laraue.Apps.Boards.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_onboardings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Attachment", b =>
                {
                    b.Navigation("IssueAttachment");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Attribute", b =>
                {
                    b.Navigation("AttributeListValues");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Epic", b =>
                {
                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.File", b =>
                {
                    b.Navigation("TelegramFile");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Issue", b =>
                {
                    b.Navigation("DateAttributes");

                    b.Navigation("DateTimeAttributes");

                    b.Navigation("DecimalAttributes");

                    b.Navigation("IntegerAttributes");

                    b.Navigation("IssueAttachments");

                    b.Navigation("IssueComments");

                    b.Navigation("IssueNumber");

                    b.Navigation("ListAttributes");

                    b.Navigation("TextAttributes");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.IssueComment", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Organization", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Spaces");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.OrganizationLog", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Retro", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroCard", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.RetroSection", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Space", b =>
                {
                    b.Navigation("Epics");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.Status", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.TelegramMessage", b =>
                {
                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.Boards.DataAccess.Models.User", b =>
                {
                    b.Navigation("Epics");

                    b.Navigation("Organizations");

                    b.Navigation("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
