//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laraue.Apps.Boards.WebApiServices.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Laraue.Apps.Boards.WebApiServices.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        internal static string EntityNotAccessible {
            get {
                return ResourceManager.GetString("EntityNotAccessible", resourceCulture);
            }
        }
        
        internal static string EntityNotFoundOrNotAccessible {
            get {
                return ResourceManager.GetString("EntityNotFoundOrNotAccessible", resourceCulture);
            }
        }
        
        internal static string EntityActionForbidden {
            get {
                return ResourceManager.GetString("EntityActionForbidden", resourceCulture);
            }
        }
        
        internal static string ProfileServiceUnavailable {
            get {
                return ResourceManager.GetString("ProfileServiceUnavailable", resourceCulture);
            }
        }
        
        internal static string AiSummarizationUnavailable {
            get {
                return ResourceManager.GetString("AiSummarizationUnavailable", resourceCulture);
            }
        }
        
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        internal static string TitleCannotBeGenerated {
            get {
                return ResourceManager.GetString("TitleCannotBeGenerated", resourceCulture);
            }
        }
        
        internal static string TitleGenerationNoCredits {
            get {
                return ResourceManager.GetString("TitleGenerationNoCredits", resourceCulture);
            }
        }
        
        internal static string InsufficientTokenBalance {
            get {
                return ResourceManager.GetString("InsufficientTokenBalance", resourceCulture);
            }
        }
        
        internal static string IssueLimitExceeded {
            get {
                return ResourceManager.GetString("IssueLimitExceeded", resourceCulture);
            }
        }
        
        internal static string OrganizationLimitExceeded {
            get {
                return ResourceManager.GetString("OrganizationLimitExceeded", resourceCulture);
            }
        }
        
        internal static string SpaceCreationForbiddenCannotMove {
            get {
                return ResourceManager.GetString("SpaceCreationForbiddenCannotMove", resourceCulture);
            }
        }
        
        internal static string AlreadyOrganizationMember {
            get {
                return ResourceManager.GetString("AlreadyOrganizationMember", resourceCulture);
            }
        }
        
        internal static string OwnerAccessCannotBeRevoked {
            get {
                return ResourceManager.GetString("OwnerAccessCannotBeRevoked", resourceCulture);
            }
        }
        
        internal static string UserNotFoundInOrganization {
            get {
                return ResourceManager.GetString("UserNotFoundInOrganization", resourceCulture);
            }
        }
        
        internal static string SpaceDirectPermissionEntityNotFound {
            get {
                return ResourceManager.GetString("SpaceDirectPermissionEntityNotFound", resourceCulture);
            }
        }
        
        internal static string SpaceDeletePermissionOnDefaultForbidden {
            get {
                return ResourceManager.GetString("SpaceDeletePermissionOnDefaultForbidden", resourceCulture);
            }
        }
        
        internal static string ListAttributeRequiresOptions {
            get {
                return ResourceManager.GetString("ListAttributeRequiresOptions", resourceCulture);
            }
        }
        
        internal static string OnlyListAttributeHasOptions {
            get {
                return ResourceManager.GetString("OnlyListAttributeHasOptions", resourceCulture);
            }
        }
        
        internal static string AdminAccessRequired {
            get {
                return ResourceManager.GetString("AdminAccessRequired", resourceCulture);
            }
        }
        
        internal static string SpaceNotExistsForMove {
            get {
                return ResourceManager.GetString("SpaceNotExistsForMove", resourceCulture);
            }
        }
        
        internal static string EpicNotExistsForMove {
            get {
                return ResourceManager.GetString("EpicNotExistsForMove", resourceCulture);
            }
        }
        
        internal static string SourceDestinationSpaceSame {
            get {
                return ResourceManager.GetString("SourceDestinationSpaceSame", resourceCulture);
            }
        }
        
        internal static string SpaceNotExistsOrEpicCreationForbidden {
            get {
                return ResourceManager.GetString("SpaceNotExistsOrEpicCreationForbidden", resourceCulture);
            }
        }
        
        internal static string FileSizeLimited {
            get {
                return ResourceManager.GetString("FileSizeLimited", resourceCulture);
            }
        }
        
        internal static string UnsupportedMimeTypes {
            get {
                return ResourceManager.GetString("UnsupportedMimeTypes", resourceCulture);
            }
        }
        
        internal static string UserNotBelongsToOrganization {
            get {
                return ResourceManager.GetString("UserNotBelongsToOrganization", resourceCulture);
            }
        }
        
        internal static string CommentNotAvailableToEdit {
            get {
                return ResourceManager.GetString("CommentNotAvailableToEdit", resourceCulture);
            }
        }
        
        internal static string CommentNotAvailableToDelete {
            get {
                return ResourceManager.GetString("CommentNotAvailableToDelete", resourceCulture);
            }
        }
        
        internal static string FilterNotFound {
            get {
                return ResourceManager.GetString("FilterNotFound", resourceCulture);
            }
        }
        
        internal static string StringFilterExpected {
            get {
                return ResourceManager.GetString("StringFilterExpected", resourceCulture);
            }
        }
        
        internal static string EnumFilterExpected {
            get {
                return ResourceManager.GetString("EnumFilterExpected", resourceCulture);
            }
        }
        
        internal static string IntegerFilterExpected {
            get {
                return ResourceManager.GetString("IntegerFilterExpected", resourceCulture);
            }
        }
        
        internal static string DecimalFilterExpected {
            get {
                return ResourceManager.GetString("DecimalFilterExpected", resourceCulture);
            }
        }
        
        internal static string DateFilterExpected {
            get {
                return ResourceManager.GetString("DateFilterExpected", resourceCulture);
            }
        }
        
        internal static string DateTimeFilterExpected {
            get {
                return ResourceManager.GetString("DateTimeFilterExpected", resourceCulture);
            }
        }
        
        internal static string SpaceNotExists {
            get {
                return ResourceManager.GetString("SpaceNotExists", resourceCulture);
            }
        }
        
        internal static string GoogleIdTokenInvalid {
            get {
                return ResourceManager.GetString("GoogleIdTokenInvalid", resourceCulture);
            }
        }
        
        internal static string GoogleCredentialMissing {
            get {
                return ResourceManager.GetString("GoogleCredentialMissing", resourceCulture);
            }
        }
    }
}
