//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laraue.Apps.Retro.WebApiServices.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laraue.Apps.Retro.WebApiServices.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string RetroFinished {
            get {
                return ResourceManager.GetString("RetroFinished", resourceCulture);
            }
        }

        internal static string RetroVoteTimerNotRunning {
            get {
                return ResourceManager.GetString("RetroVoteTimerNotRunning", resourceCulture);
            }
        }

        internal static string RetroVoteLimitReached {
            get {
                return ResourceManager.GetString("RetroVoteLimitReached", resourceCulture);
            }
        }

        internal static string RetroCardDoneUnavailable {
            get {
                return ResourceManager.GetString("RetroCardDoneUnavailable", resourceCulture);
            }
        }

        internal static string RetroPhaseTransitionInvalid {
            get {
                return ResourceManager.GetString("RetroPhaseTransitionInvalid", resourceCulture);
            }
        }

        internal static string RetroFinishUnavailable {
            get {
                return ResourceManager.GetString("RetroFinishUnavailable", resourceCulture);
            }
        }

        internal static string RetroCardsFrozen {
            get {
                return ResourceManager.GetString("RetroCardsFrozen", resourceCulture);
            }
        }

        internal static string RetroGroupInvalid {
            get {
                return ResourceManager.GetString("RetroGroupInvalid", resourceCulture);
            }
        }

        internal static string RetroActionsPhaseOnly {
            get {
                return ResourceManager.GetString("RetroActionsPhaseOnly", resourceCulture);
            }
        }

        internal static string RetroActionAlwaysVisible {
            get {
                return ResourceManager.GetString("RetroActionAlwaysVisible", resourceCulture);
            }
        }

        internal static string RetroActionsSectionOnly {
            get {
                return ResourceManager.GetString("RetroActionsSectionOnly", resourceCulture);
            }
        }

        internal static string RetroNameRequired {
            get {
                return ResourceManager.GetString("RetroNameRequired", resourceCulture);
            }
        }

        internal static string RetroFacilitatorNotParticipant {
            get {
                return ResourceManager.GetString("RetroFacilitatorNotParticipant", resourceCulture);
            }
        }

        internal static string RetroAssigneeNotParticipant {
            get {
                return ResourceManager.GetString("RetroAssigneeNotParticipant", resourceCulture);
            }
        }

        internal static string RetroSectionNotInRetro {
            get {
                return ResourceManager.GetString("RetroSectionNotInRetro", resourceCulture);
            }
        }

        internal static string RetroCardCoordinatesInvalid {
            get {
                return ResourceManager.GetString("RetroCardCoordinatesInvalid", resourceCulture);
            }
        }

        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }

        internal static string EntityNotFoundOrNotAccessible {
            get {
                return ResourceManager.GetString("EntityNotFoundOrNotAccessible", resourceCulture);
            }
        }

        internal static string EntityActionForbidden {
            get {
                return ResourceManager.GetString("EntityActionForbidden", resourceCulture);
            }
        }
    }
}
