//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laraue.Apps.Boards.TelegramServices.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laraue.Apps.Boards.TelegramServices.Resources.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Created {0} in {1}.
        /// </summary>
        internal static string CardCreated {
            get {
                return ResourceManager.GetString("CardCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose category.
        /// </summary>
        internal static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose status.
        /// </summary>
        internal static string ChooseStatus {
            get {
                return ResourceManager.GetString("ChooseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat is already linked to.
        /// </summary>
        internal static string LinkAlreadyLinked {
            get {
                return ResourceManager.GetString("LinkAlreadyLinked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ⬅ Back.
        /// </summary>
        internal static string LinkBack {
            get {
                return ResourceManager.GetString("LinkBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🔄 Change link.
        /// </summary>
        internal static string LinkChangeLink {
            get {
                return ResourceManager.GetString("LinkChangeLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose an organization to link this chat to:.
        /// </summary>
        internal static string LinkChooseOrganization {
            get {
                return ResourceManager.GetString("LinkChooseOrganization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How should cards from this chat land in {0}?.
        /// </summary>
        internal static string LinkChooseDestinationDepth {
            get {
                return ResourceManager.GetString("LinkChooseDestinationDepth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose an epic:.
        /// </summary>
        internal static string LinkChooseEpic {
            get {
                return ResourceManager.GetString("LinkChooseEpic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🗂 Choose epic &amp; status.
        /// </summary>
        internal static string LinkChooseEpicAndStatus {
            get {
                return ResourceManager.GetString("LinkChooseEpicAndStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose a space in {0}:.
        /// </summary>
        internal static string LinkChooseSpace {
            get {
                return ResourceManager.GetString("LinkChooseSpace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose a status in {0}:.
        /// </summary>
        internal static string LinkChooseStatus {
            get {
                return ResourceManager.GetString("LinkChooseStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✅ This chat is now linked to.
        /// </summary>
        internal static string LinkConfirmed {
            get {
                return ResourceManager.GetString("LinkConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You don't have access to any organizations yet. Open @{0} in a private chat and create or join one first..
        /// </summary>
        internal static string LinkNoOrganizations {
            get {
                return ResourceManager.GetString("LinkNoOrganizations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only chat admins can link this chat to an organization. Ask an admin to run /link..
        /// </summary>
        internal static string LinkOnlyAdmins {
            get {
                return ResourceManager.GetString("LinkOnlyAdmins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This chat is no longer linked to any organization or space..
        /// </summary>
        internal static string LinkUnlinked {
            get {
                return ResourceManager.GetString("LinkUnlinked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ❌ Unlink.
        /// </summary>
        internal static string LinkUnlinkButton {
            get {
                return ResourceManager.GetString("LinkUnlinkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This chat isn't linked to an organization yet. An admin can run /link to set it up..
        /// </summary>
        internal static string MentionChatNotLinked {
            get {
                return ResourceManager.GetString("MentionChatNotLinked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To create a card, reply to the message you want to turn into an issue and mention me in that reply..
        /// </summary>
        internal static string MentionReplyRequired {
            get {
                return ResourceManager.GetString("MentionReplyRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I can't turn this message type into a card yet..
        /// </summary>
        internal static string MentionUnsupportedType {
            get {
                return ResourceManager.GetString("MentionUnsupportedType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 📥 Use backlog (default).
        /// </summary>
        internal static string LinkUseBacklog {
            get {
                return ResourceManager.GetString("LinkUseBacklog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        internal static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Status.
        /// </summary>
        internal static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Message Board.
        /// </summary>
        internal static string OpenMiniApp {
            get {
                return ResourceManager.GetString("OpenMiniApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send category name.
        /// </summary>
        internal static string SendCategoryName {
            get {
                return ResourceManager.GetString("SendCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send new text.
        /// </summary>
        internal static string SendNewText {
            get {
                return ResourceManager.GetString("SendNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status name.
        /// </summary>
        internal static string SendStatusName {
            get {
                return ResourceManager.GetString("SendStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 Hey! I&apos;m Message Board Bot.
        ///
        ///I help you turn important Telegram messages into organized Kanban boards. Message me or forward a message and I&apos;ll add it to your Board.
        ///
        ///You can create boards, use full-text search, and much more. And never get lost in your notes again.
        ///
        ///Tap the button below to open your board 👇.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Categories.
        /// </summary>
        internal static string YourCategories {
            get {
                return ResourceManager.GetString("YourCategories", resourceCulture);
            }
        }
    }
}
